### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-marinarodriguez#1]
Buen trabajo @marinarodriguez 

Algunas pistas para acabarlo:

- [x] Mueve la etiqueta main fuera de PokemonList
- [x] La prop `key` no la podemos recoger, es para react, si necesitas ese mismo valor tienes que añadir otra prop, por ejemplo `id`. En cualquier caso key solo es necesario en la primera etiqueta de cada item cuando hacemos un map.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Revisa la consola de Chrome y tus PropTypes.
- [x] Elimina el código comentado
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by marinarodriguez** [comment]
Creo que ya están todos los issues resueltos, he movido el array y lo he guardado como estado. Voy a ponerme con los otros 3 puntos del final en otra rama, pero ya puedes revisarlo.

:+1:

**Comment by nasivuela** [comment]
Excelente trabajo @marinarodriguez !!

Como última recomendación, crea un archivo CSS para cada componente. Haz que cada componente importe su propio CSS y que esté junto a este en las carpetas ;)

![](https://media.giphy.com/media/MgX8LzWrA6dgY/giphy.gif)
